# Generated by Django 5.0.6 on 2024-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_railway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railway',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
