# Generated by Django 5.0.6 on 2024-06-03 22:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_railway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railway',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
