# Generated by Django 5.0.6 on 2024-06-03 22:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_railway_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prohibited',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('layer', models.CharField(max_length=254)),
                ('path', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Recomended',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
