# Generated by Django 5.0.6 on 2024-06-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_prohibited_recomended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibited',
            name='layer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prohibited',
            name='path',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
