# Generated by Django 5.0.6 on 2024-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_boundaryarea_riverarea_warningarea_delete_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningarea',
            name='layer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warningarea',
            name='path',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
