# Generated by Django 5.0.6 on 2024-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_warningarea_layer_alter_warningarea_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibited',
            name='pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prohibited',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
