# Generated by Django 5.0.6 on 2024-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_remove_prohibited_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibited',
            name='pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
