# Generated by Django 5.0.6 on 2024-07-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_prohibited_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prohibited',
            options={'verbose_name_plural': 'Prohibited Area'},
        ),
    ]
